### PR TITLE
Fix TLDR for new install script

### PR DESCRIPTION
**Pull request by zehicle**
after testing this page, I made a lot of changes based on recent updates:

update quickstart for 16.04, new script, new ux, k8s instead of swarm and other tweaks.

Still need to validate the ports!

### CODE REVIEW

**Comment by zehicle** [comment]
@galthaus this changes for your new script and one line process.  
looks MUCH easier.  works great on 16.04

**Comment by galthaus** [comment]
14.04 - just needs to be run twice.

**Comment by ravolt** [comment]
I could not verify that when I tried.On September 18, 2016 at 9:02 PM Greg Althaus <notifications@github.com> wrote:14.04 - just needs to be run twice.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by galthaus** [comment]
What did it do?  I can see it fail and I tried it again and it work.  It would be go to know how it failed.

**Pull request merged**
